// Counts everything act 6 prints, straight off the CURRICULUM REPO's 213 authored session
// files, and writes app/data/inventory.json. Act 6's whole authority is that its figures are
// checkable, and catalog.json carries metadata only — no teaching_flow, no puzzle tiers, no
// homework — so a roll-up cannot be counted from app/data alone. This is that roll-up's
// generator, the same contract catalog.json has: generated by a script, never edited by hand.
//
// usage: node tools/inventory.cjs          # count, write app/data/inventory.json
//        node tools/inventory.cjs --check  # count, diff against the file, exit 1 on drift
//
// Source of truth: C:/Users/MUS/ChessCurriculumProject/curriculum/Stage_{1..5}/**.json
// (213 files, bundle 1.1.0). Override with SRC=<path to curriculum dir>.
const fs = require('fs');
const path = require('path');

const SRC = process.env.SRC || 'C:/Users/MUS/ChessCurriculumProject/curriculum';
const OUT = path.join(__dirname, '..', 'app', 'data', 'inventory.json');
const CHECK = process.argv.includes('--check');

function files() {
  const out = [];
  for (const st of ['Stage_1', 'Stage_2', 'Stage_3', 'Stage_4', 'Stage_5']) {
    const d = path.join(SRC, st);
    if (!fs.existsSync(d)) continue;
    const walk = (p) => {
      for (const e of fs.readdirSync(p, { withFileTypes: true })) {
        const q = path.join(p, e.name);
        if (e.isDirectory()) walk(q);
        else if (e.name.endsWith('.json')) out.push(q);
      }
    };
    walk(d);
  }
  return out.sort();
}

// The eight segments a session is EXPERIENCED in, counted exactly the way
// app/js/teach/segments.js counts them, so the site and this file cannot disagree.
function segmentsOf(L) {
  const f = L.teaching_flow || {};
  let n = 0;
  const rv = f.warmup_review;
  if (rv && (rv.description || (rv.review_items || []).length)) n++;
  if (f.lesson_introduction) n++;
  if (f.core_explanation) n++;
  if (f.guided_discussion) n++;
  if ((f.guided_examples || []).length) n++;
  if ((L.puzzles || []).length) n++;
  if (L.practical_activity) n++;
  n++; // homework, always emitted
  return n;
}

const list = files();
const acc = {
  sessions: 0, puzzles: 0, tiers: { Foundation: 0, Core: 0, Challenge: 0 },
  segments: 0, questions: 0, activities: 0, homework: 0,
  homeworkOnline: 0, homeworkBoard: 0, homeworkReflect: 0, homeworkOptional: 0,
  homeworkMinutes: 0, simplify: 0, extend: 0, misconceptions: 0,
  minutesPlanned: 0, prereq: 0, demos: 0, outcomes: 0,
};
const durations = [];
const ageBands = {};
const routines = {};

for (const f of list) {
  let L;
  try { L = JSON.parse(fs.readFileSync(f, 'utf8')); } catch { continue; }
  if (!L.id) continue;
  acc.sessions++;
  acc.segments += segmentsOf(L);
  const pz = L.puzzles || [];
  acc.puzzles += pz.length;
  for (const p of pz) if (acc.tiers[p.difficulty] !== undefined) acc.tiers[p.difficulty]++;
  const fl = L.teaching_flow || {};
  acc.questions += (fl.questions_to_ask || []).length;
  acc.demos += ((fl.core_explanation || {}).demonstrations || []).length
    + (fl.guided_examples || []).length;
  if (L.practical_activity) acc.activities++;
  const hw = L.homework;
  if (hw) {
    acc.homework++;
    if ((hw.online_practice || []).length) acc.homeworkOnline++;
    if ((hw.over_the_board || []).length) acc.homeworkBoard++;
    if ((hw.reflection_questions || []).length) acc.homeworkReflect++;
    if ((hw.optional_challenge || []).length) acc.homeworkOptional++;
    acc.homeworkMinutes += hw.estimated_time_min || 0;
  }
  const cn = L.coach_notes || {};
  if ((cn.ways_to_simplify || []).length) acc.simplify++;
  if ((cn.extensions_for_strong_students || []).length) acc.extend++;
  if ((cn.common_misconceptions || []).length) acc.misconceptions++;
  acc.outcomes += (L.expected_outcomes || []).length;
  acc.prereq += ((L.prerequisites || {}).sessions || []).length ? 1 : 0;
  if (L.estimated_duration_min) {
    durations.push(L.estimated_duration_min);
    acc.minutesPlanned += L.estimated_duration_min;
  }
  if (L.age_band) ageBands[L.age_band] = (ageBands[L.age_band] || 0) + 1;
  const tr = (L.thinking_routine || {}).current;
  if (tr) routines[tr] = (routines[tr] || 0) + 1;
}

const mode = (a) => {
  const c = {};
  for (const v of a) c[v] = (c[v] || 0) + 1;
  return Number(Object.entries(c).sort((x, y) => y[1] - x[1])[0][0]);
};

const built = {
  $comment: 'GENERATED by tools/inventory.cjs from the curriculum repo\'s 213 authored session'
    + ' files — do not edit. Re-run `node tools/inventory.cjs --check` to prove it still counts.',
  _source: SRC,
  bundle_version: '1.1.0',
  sessions: acc.sessions,
  segments: acc.segments,
  puzzles: acc.puzzles,
  tiers: acc.tiers,
  questions: acc.questions,
  demonstrations: acc.demos,
  activities: acc.activities,
  outcomes: acc.outcomes,
  homework: {
    sessions: acc.homework,
    online: acc.homeworkOnline,
    overTheBoard: acc.homeworkBoard,
    reflection: acc.homeworkReflect,
    optional: acc.homeworkOptional,
    minutes: acc.homeworkMinutes,
  },
  coachNotes: {
    waysToSimplify: acc.simplify,
    extensions: acc.extend,
    misconceptions: acc.misconceptions,
  },
  minutes: {
    planned: acc.minutesPlanned,
    min: durations.length ? Math.min(...durations) : 0,
    max: durations.length ? Math.max(...durations) : 0,
    mode: durations.length ? mode(durations) : 0,
  },
  ageBands,
  thinkingRoutines: routines,
};

if (CHECK) {
  if (!fs.existsSync(OUT)) { console.error('FAIL no ' + OUT); process.exit(1); }
  const have = JSON.parse(fs.readFileSync(OUT, 'utf8'));
  const strip = (o) => { const c = { ...o }; delete c.$comment; delete c._source; return c; };
  const a = JSON.stringify(strip(have), null, 1);
  const b = JSON.stringify(strip(built), null, 1);
  if (a === b) { console.log('inventory.json matches the curriculum repo — ' + acc.sessions + ' sessions counted'); process.exit(0); }
  console.error('DRIFT — inventory.json does not match the count.\n--- file ---\n' + a + '\n--- counted ---\n' + b);
  process.exit(1);
}

fs.writeFileSync(OUT, JSON.stringify(built, null, 1) + '\n');
console.log(JSON.stringify(built, null, 1));
console.log('\nwrote ' + OUT);
